name: redstonex
description: 基于GetX的Flutter快速开发框架。Development flutter framework based GetX frame.
version: 1.0.9
homepage: https://github.com/Chaos-woo/redstonex

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: ^0.2.0
  # 资源处理插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.1.8
  # iOS风格icon
  cupertino_icons: ^1.0.5
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.3.1
  # 网络库，相关插件见https://github.com/flutterchina/dio/blob/master/README-ZH.md
  # https://github.com/flutterchina/dio
  dio: ^4.0.6
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.1.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars_flutter3: ^3.0.0 # flustars很久不维护，可以使用这个替代
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.8.5+3
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^4.0.2
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.3.0+2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^7.0.0
  # App Shortcuts桌面快捷方式 https://github.com/flutter/plugins/tree/master/packages/quick_actions
  quick_actions: ^1.0.0
  # 权限处理 https://github.com/baseflow/flutter-permission-handler
  permission_handler: ^10.0.0
  # 设备网络连接状态 https://plus.fluttercommunity.dev/
  connectivity_plus: ^2.3.5
  # 设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: ^4.0.0
  # 应用包信息 https://plus.fluttercommunity.dev/
  package_info_plus: ^1.4.2
  # 设备网络信息 https://plus.fluttercommunity.dev/
  network_info_plus: ^2.1.3
  # 注解式本地数据库 https://pub.dev/packages/floor
  floor: ^1.3.0
  # 状态管理，路由管理 https://github.com/jonataslaw/getx
  get: ^4.6.5
  # 内存存储 https://github.com/jonataslaw/get_storage
  get_storage: ^2.0.3
  # pojo <-> json处理：https://pub.dev/packages/json_serializable
  # json注解使用：https://github.com/google/json_serializable.dart/blob/master/example/lib/example.dart
  json_annotation: ^4.6.0
  # 事件总线 https://code.makery.ch/library/dart-event-bus/
  event_bus: ^2.0.0
  # SQLite本地数据库 https://github.com/tekartik/sqflite/tree/master/sqflite
  sqflite: ^2.0.3
  sqflite_common: ^2.4.2+2
  # 应用路径处理，例如临时目录、应用内部文件路径
  path_provider: ^2.0.11
  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^3.0.6
  # 加解密处理 https://github.com/leocavalcante/encrypt
  encrypt: ^5.0.1
  # svg图片处理 https://github.com/dnfield/flutter_svg
  flutter_svg: ^1.1.6
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.1.0
  # 简易使用loading加载 https://github.com/nslogx/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 下拉、上拉加载 https://github.com/xxzj990-game/flutter_pulltorefresh
  pull_to_refresh_flutter3: ^2.0.1
  # UI布局语法糖 https://github.com/ReinBentdal/styled_widget
  styled_widget: ^0.4.1
  # 数字展示处理 https://github.com/entronad/number_display
  number_display: ^3.0.0
  # 支持tuple结构 https://github.com/avdosev/tuple_dart
  tuple_dart: ^1.4.2

dev_dependencies:
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  analyzer: 4.3.1
  flutter_lints: 2.0.0
  # json序列化/反序列化代码生成处理器
  json_serializable: 6.3.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: any #^2.1.11
  # floor数据库代码生成器
  floor_generator: 1.3.0

# dart脚本运行IDE插件
scripts:
  build_runner_build: flutter packages pub run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
