// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'dart:async' as prefix10;
import 'package:get/get_navigation/src/routes/get_route.dart' as prefix8;
import 'package:redstonex/app-configs/global_config.dart' as prefix12;
import 'package:redstonex/app-configs/initializer/configs/builtin_config.dart'
    as prefix1;
import 'package:redstonex/app-configs/initializer/properties/def_global_config_initializer.dart'
    as prefix3;
import 'package:redstonex/ioc-core/metadata-core/carriers/named_reference.dart'
    as prefix11;
import 'package:redstonex/ioc-core/metadata-core/carriers/post_construct.dart'
    as prefix7;
import 'package:redstonex/ioc-core/metadata-core/component.dart' as prefix0;
import 'package:redstonex/ioc-core/metadata-core/components_configuration.dart'
    as prefix2;
import 'package:redstonex/ioc-core/metadata-core/reflector.dart' as prefix5;
import 'package:redstonex/ioc-core/metadata-core/static_reflection.dart'
    as prefix6;
import 'package:redstonex/route-core/dispatcher.dart' as prefix4;
import 'package:redstonex/route-core/route_holder.dart' as prefix9;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Component(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'BuiltinConfiguration',
            r'.BuiltinConfiguration',
            134217735,
            0,
            const prefix0.Component(),
            const <int>[4, 5],
            const <int>[6, 7, 8, 9, 10, 4],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.BuiltinConfiguration() : null},
            0,
            0,
            const <int>[],
            const <Object>[const prefix0.Component()],
            null),
        r.NonGenericClassMirrorImpl(
            r'Dispatcher',
            r'.Dispatcher',
            134217735,
            1,
            const prefix0.Component(),
            const <int>[0, 1, 2, 3, 11, 12, 13, 18],
            const <int>[6, 7, 8, 9, 10, 11, 12, 13],
            const <int>[14, 15, 16, 17],
            -1,
            {
              r'pageRoutes': () => prefix4.Dispatcher.pageRoutes,
              r'routeGroups': () => prefix4.Dispatcher.routeGroups,
              r'otherRouteGroup': () => prefix4.Dispatcher.otherRouteGroup,
              r'statistics': () => prefix4.Dispatcher.statistics
            },
            {},
            {r'': (bool b) => () => b ? prefix4.Dispatcher() : null},
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.Component()],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'pageRoutes', 151127061, 1,
            const prefix0.Component(), -1, 2, 3, null, const []),
        r.VariableMirrorImpl(r'routeGroups', 151127061, 1,
            const prefix0.Component(), -1, 4, 5, const <int>[6], const []),
        r.VariableMirrorImpl(r'otherRouteGroup', 134349845, 1,
            const prefix0.Component(), -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'statistics', 134349845, 1,
            const prefix0.Component(), -1, 7, 7, const <int>[], const []),
        r.MethodMirrorImpl(
            r'initialize',
            35651586,
            0,
            -1,
            8,
            9,
            const <int>[-1],
            const <int>[],
            const prefix0.Component(),
            const <Object>[const prefix7.PostConstruct()]),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 10, 10, const <int>[],
            const <int>[0], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 11, 11, const <int>[],
            const <int>[], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1,
            const <int>[], const <int>[1], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 12, 12, const <int>[],
            const <int>[], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 13, 13,
            const <int>[], const <int>[], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'group', 2097154, 1, -1, 6, 6, const <int>[],
            const <int>[2], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'route', 1310722, 1, -1, -1, -1, const <int>[],
            const <int>[3], const prefix0.Component(), const []),
        r.MethodMirrorImpl(r'init', 1310722, 1, -1, -1, -1, const <int>[],
            const <int>[], const prefix0.Component(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Component(), 0, 14),
        r.ImplicitGetterMirrorImpl(const prefix0.Component(), 1, 15),
        r.ImplicitGetterMirrorImpl(const prefix0.Component(), 2, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.Component(), 3, 17),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, const <int>[], const <int>[],
            const prefix0.Component(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'other', 134348806, 6, const prefix0.Component(),
            -1, 14, 14, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            8,
            const prefix0.Component(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'groupName',
            67252230,
            11,
            const prefix0.Component(),
            -1,
            16,
            16,
            const <int>[],
            const [],
            null,
            #groupName),
        r.ParameterMirrorImpl(
            r'route',
            134348806,
            12,
            const prefix0.Component(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.BuiltinConfiguration,
        prefix4.Dispatcher,
        const m.TypeValue<List<prefix8.GetPage<dynamic>>>().type,
        List,
        const m.TypeValue<List<prefix9.RouteGroupHolder>>().type,
        List,
        prefix9.RouteGroupHolder,
        prefix4.RoutesStatistics,
        const m.TypeValue<prefix10.Future<void>>().type,
        prefix10.Future,
        bool,
        String,
        int,
        Type,
        Object,
        Invocation,
        String,
        prefix9.RouteHolder
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'initialize': (dynamic instance) => instance.initialize,
        r'group': (dynamic instance) => instance.group,
        r'route': (dynamic instance) => instance.route,
        r'init': (dynamic instance) => instance.init
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Component(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://1/'),
            const prefix0.Component(), const <int>[], {}, {}, const [], null)
      ],
      []),
  const prefix2.ComponentsConfiguration(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DefGlobalConfigInitializer',
            r'.DefGlobalConfigInitializer',
            134217735,
            0,
            const prefix2.ComponentsConfiguration(),
            const <int>[0, 1],
            const <int>[2, 3, 4, 5, 6, 0],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix3.DefGlobalConfigInitializer() : null
            },
            0,
            0,
            const <int>[],
            const <Object>[const prefix2.ComponentsConfiguration()],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(
            r'globalConfig',
            2097154,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix2.ComponentsConfiguration(),
            const <Object>[
              const prefix0.Component(),
              const prefix11.NamedReference(
                  name: prefix12.GlobalConfig.fixedGlobalConfigTag)
            ]),
        r.MethodMirrorImpl(r'', 64, 0, -1, -1, -1, null, const <int>[],
            const prefix2.ComponentsConfiguration(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[0],
            const prefix2.ComponentsConfiguration(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix2.ComponentsConfiguration(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[1], const prefix2.ComponentsConfiguration(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix2.ComponentsConfiguration(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix2.ComponentsConfiguration(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            2,
            const prefix2.ComponentsConfiguration(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            4,
            const prefix2.ComponentsConfiguration(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix3.DefGlobalConfigInitializer],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'globalConfig': (dynamic instance) => instance.globalConfig
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(r'reflectable://0/'),
            const prefix2.ComponentsConfiguration(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      []),
  const prefix5.Reflector(): r.ReflectorData(
      <m.TypeMirror>[],
      <m.DeclarationMirror>[],
      <m.ParameterMirror>[],
      <Type>[],
      0,
      {},
      {},
      <m.LibraryMirror>[],
      []),
  const prefix6.StaticReflection(): r.ReflectorData(
      <m.TypeMirror>[],
      <m.DeclarationMirror>[],
      <m.ParameterMirror>[],
      <Type>[],
      0,
      {},
      {},
      <m.LibraryMirror>[],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
